#!/usr/bin/env python3
"""Cuts the CJK glyphs that textos.py uses out of the full Fusion Pixel Font 12px (zh_hans,
monospaced, BDF) into fonts/fusion-pixel-12px-zh_hans-subset.bdf, the only copy kept in the repo.
Stdlib only.

    python3 tools/oled/cjk_subset.py <fusion-pixel-12px-monospaced-zh_hans.bdf>
    python3 tools/oled/gen_assets.py lib/ProtoTracer/ExternalDevices/Displays

Run it after adding Chinese text to textos.py (where to get the font: fonts/README.md). Every
character of textos.py that font5x7.py does not draw has to be in the full font, or this stops.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import bdf  # noqa: E402
import textos  # noqa: E402
from font5x7 import G as LATIN  # noqa: E402

SUBSET = os.path.join(HERE, "fonts", "fusion-pixel-12px-zh_hans-subset.bdf")


def all_strings():
    """(where, text) of every string in textos.py."""
    out = []
    for name, t in textos.FACES.items():
        out += [(f"FACES[{name}][{textos.LANGS[i]}]", s) for i, s in enumerate(t) if s]
    for group in ("SETTINGS", "COLORS", "HUES", "EFFECTS"):
        for k, t in enumerate(getattr(textos, group)):
            out += [(f"{group}[{k}][{textos.LANGS[i]}]", s) for i, s in enumerate(t) if s]
    for name, t in textos.WORDS.items():
        out += [(f"WORDS[{name}][{textos.LANGS[i]}]", s) for i, s in enumerate(t) if s]
    return out


def cjk_chars():
    """Characters font5x7.py does not have (lowercase a-z count as caps, like FindGlyph)."""
    need = {}
    for where, s in all_strings():
        for ch in s:
            up = ch.upper() if "a" <= ch <= "z" else ch
            if up not in LATIN:
                need.setdefault(ch, where)
    return need


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    header, glyphs, _, _ = bdf.read(sys.argv[1])
    need = cjk_chars()
    missing = [f"{ch} (U+{ord(ch):04X}, {where})" for ch, where in sorted(need.items()) if ord(ch) not in glyphs]
    if missing:
        sys.exit("not in the full font either:\n  " + "\n  ".join(missing))
    version = next((ln.split(None, 1)[1].strip('"') for ln in header if ln.startswith("FONT_VERSION")), "?")
    os.makedirs(os.path.dirname(SUBSET), exist_ok=True)
    bdf.write(SUBSET, header, [glyphs[ord(ch)] for ch in need], comments=[
        f"Subset of Fusion Pixel Font 12px monospaced zh_hans {version} (SIL OFL 1.1, see OFL.txt)",
        "https://github.com/TakWolf/fusion-pixel-font - only the characters tools/oled/textos.py uses",
        "Generated by tools/oled/cjk_subset.py; glyphs unchanged",
    ])
    print(f"{len(need)} glyphs -> {os.path.relpath(SUBSET)}: {''.join(sorted(need))}")


if __name__ == "__main__":
    main()
