#!/usr/bin/env python3
"""Generates SoftAssets.h + SoftAssets.cpp (fonts, icons, baked widgets) for the OLED HUD.

    python3 tools/oled/gen_assets.py lib/ProtoTracer/ExternalDevices/Displays

Sources (edit these, not the generated files):
  textos.py   every word on the screen, in each language (es, en, zh)
  font5x7.py  hand-drawn 5x7 caps (+ accents, the private glyphs \\x01-\\x05)
  fonts/      the Chinese characters textos.py uses (Fusion Pixel 12px subset, OFL-1.1; how to
              add more: fonts/README.md)
  icons.py    16x16 setting icons, 12x12 pictograms (+ native 2 px ones), sparkles, the
              coolant warning light, the boop status line (hand + check)
  fan.py      the fan icon (procedural, 3 rotation frames)
  softpix.py  EPX 2x smoother + exact ports of the Adafruit_GFX primitives
Big font, setting icons and pictograms are the EPX 2x of the 1 px art, so they share one
soft 2 px stroke. Widgets are drawn with the GFX ports and stored as bitmaps, so the GFX
circle/round-rect code is never linked. Needs numpy. Output is deterministic.

Stops with an error (and writes nothing) if a string of textos.py uses a character without a
glyph or does not fit the screen: that shows up here, never on the head.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from font5x7 import G as GLYPHS  # noqa: E402
import icons  # noqa: E402
from icons import BP, I, P, PN, S, T  # noqa: E402
from fan import fan  # noqa: E402
from softpix import G, crop, epx, pack, parse, recenter  # noqa: E402
import bdf  # noqa: E402
import textos  # noqa: E402

out_dir = sys.argv[1] if len(sys.argv) > 1 else '.'
HERE = os.path.dirname(os.path.abspath(__file__))
CJK_BDF = os.path.join(HERE, 'fonts', 'fusion-pixel-12px-zh_hans-subset.bdf')

cpp = ['// GENERATED by tools/oled/gen_assets.py - edit the sources there, not this file.',
       '// Everything is PROGMEM: on the Teensy 4 plain const data would be copied into RAM1.',
       '#include <Arduino.h>', '#include "SoftAssets.h"', '']
hdr = ['// GENERATED by tools/oled/gen_assets.py - edit the sources there, not this file.',
       '#pragma once', '#include <stdint.h>', '',
       'struct SoftGlyph { uint16_t code; int8_t top; uint8_t w; uint8_t h; uint16_t off; };',
       'struct SoftFont { const SoftGlyph* glyphs; uint8_t count; const uint8_t* bits; uint8_t capHeight; uint8_t spacing; };',
       'struct SoftIcon { uint8_t w; uint8_t h; const uint8_t* bits; };', '',
       'extern const SoftFont softFontS;   // 5x7 soft caps',
       'extern const SoftFont softFontL;   // EPX 2x of the same (10x14)',
       'extern const SoftFont softFontCJK; // 12 px Chinese, only the characters of textos.py (Fusion Pixel Font, OFL-1.1)', '']
total = 0


def font_tables(name, scale):
    glyphs, bits = [], []
    for ch in sorted(GLYPHS, key=ord):
        a = parse(GLYPHS[ch])
        top = 7 - a.shape[0]
        if scale == 2:
            a = epx(a)
            top *= 2
        h, w = a.shape
        glyphs.append((ord(ch), top, w, h, len(bits), ch))
        bits += pack(a)
    s = [f'static const uint8_t {name}Bits[] PROGMEM = {{',
         '    ' + ', '.join(f'0x{b:02X}' for b in bits), '};',
         f'static const SoftGlyph {name}Glyphs[] PROGMEM = {{']
    for code, top, w, h, off, ch in glyphs:
        label = 'space' if ch == ' ' else (ch if ch.isprintable() and ch != '\\' else f'\\x{ord(ch):02x}')
        s.append(f'    {{0x{code:04X}, {top}, {w}, {h}, {off}}}, // {label}')
    s.append('};')
    s.append(f'PROGMEM const SoftFont {name} = {{{name}Glyphs, {len(glyphs)}, {name}Bits, {7 * scale}, {scale}}};')
    return '\n'.join(s), len(bits) + len(glyphs) * 8


for nm, sc in (('softFontS', 1), ('softFontL', 2)):
    t, n = font_tables(nm, sc)
    cpp += [t, '']
    total += n


# ---- texts (textos.py) + the Chinese glyphs they use ------------------------------------------
# Width rules: the same arithmetic as HeadsUpDisplay::TextWidth (SSD1306.cpp). A code point from
# CJK_FIRST up is drawn from softFontCJK (an 11x11 cell, 1 px gap = the font's 12 px advance) on the
# centre line of the Latin text; never bold, except the switch's active word (the "on" side).
# Closing full-width punctuation (CJK_TRIM) sits at the left of its em with the rest blank: its cell
# ends at its ink, so a word ending in ！ stays centred (CJK typesetting squeezes line-end
# punctuation the same way). The pixels are the font's in every case.
CJK_FIRST = 0x2E80   # HeadsUpDisplay::cjkFirst
CJK_W = CJK_H = 11
CJK_SPACING = 1
CJK_TRIM = {ord(c) for c in '！？，。、：；）'}
SCREEN_W = 128
BIG_MAX = SCREEN_W - 6      # face name / word: wider than this falls back to the small bold font
SWITCH_MAX = 64 - 18 - 6    # DrawToggle: room left of the 36 px pill (6 px gap), same on the right

L = len(textos.LANGS)
_, cjk_all, cjk_ascent, _ = bdf.read(CJK_BDF)
cjk_cell_top = cjk_ascent - 2          # first row of the cell, in px above the baseline
problems = []


def cjk_cell(code):
    """The glyph in its 11x11 cell (the font's 12 px em without its top row and its right column,
    the gap), so every character sits on the same baseline; CJK_TRIM cut after its ink."""
    a = np.array(cjk_all[code].cell(cjk_cell_top, CJK_H, CJK_W), np.uint8)
    if code in CJK_TRIM and a.any():
        a = a[:, :np.nonzero(a.any(0))[0].max() + 1]
    return a


def all_strings():
    """(where, text, kind) for every string of textos.py; kind tells which layout checks apply."""
    out = []
    for name, t in textos.FACES.items():
        assert len(t) == L, name
        out += [(f'FACES["{name}"][{textos.LANGS[i]}]', s, 'face') for i, s in enumerate(t) if s]
    for group, kind, n in (('SETTINGS', 'label', 13), ('COLORS', 'word', 10), ('HUES', 'word', 10), ('EFFECTS', 'word', 10)):
        rows = getattr(textos, group)
        assert len(rows) == n and all(len(t) == L for t in rows), group
        out += [(f'{group}[{k}][{textos.LANGS[i]}]', s, kind) for k, t in enumerate(rows) for i, s in enumerate(t) if s]
    kinds = {'HELLO': 'hello', 'FACE': 'face', 'OFF': 'switch', 'ON': 'switch'}
    assert list(textos.WORDS) == list(kinds), 'WORDS keys/order (C++ enum SoftWord)'
    for k, t in textos.WORDS.items():
        assert len(t) == L, k
        out += [(f'WORDS["{k}"][{textos.LANGS[i]}]', s, kinds[k]) for i, s in enumerate(t) if s]
    return out


def latin(ch):
    return ch.upper() if 'a' <= ch <= 'z' else ch   # caps-only font, like FindGlyph


cjk_used = set()
for where, s, _ in all_strings():
    for ch in s:
        if ord(ch) > 0xFFFF:
            problems.append(f'{where} = {s!r}: {ch!r} (U+{ord(ch):X}) is beyond 3-byte UTF-8, the HUD reads only up to U+FFFF')
        elif ord(ch) >= CJK_FIRST:
            if ord(ch) in cjk_all:
                cjk_used.add(ord(ch))
            else:
                problems.append(f'{where} = {s!r}: no glyph for {ch} (U+{ord(ch):04X}) in {os.path.relpath(CJK_BDF, HERE)}'
                                ' (run cjk_subset.py, see fonts/README.md)')
        elif latin(ch) not in GLYPHS:
            problems.append(f'{where} = {s!r}: no glyph for {ch!r} (U+{ord(ch):04X}) in font5x7.py')


def text_w(s, big, bold=False, cjk_bold=False):
    w, pend, first = 0, 0, True
    for ch in s:
        if ord(ch) >= CJK_FIRST and ord(ch) in cjk_all:
            gw, sp = cjk_cell(ord(ch)).shape[1] + (1 if cjk_bold else 0), CJK_SPACING
        else:
            gw = parse(GLYPHS.get(latin(ch), GLYPHS['?'])).shape[1] * (2 if big else 1) + (1 if bold else 0)
            sp = 2 if big else 1
        if not first:
            w += pend
        w += gw
        pend, first = sp, False
    return w


small_ones = []
if not problems:
    for where, s, kind in all_strings():
        big, small = text_w(s, True), text_w(s, False, True)
        if kind in ('face', 'word'):
            if big > BIG_MAX:
                small_ones.append(f'{where} = {s!r}: {big} px big -> small font ({small} px)')
                if small > SCREEN_W - 4:
                    problems.append(f'{where} = {s!r}: {small} px even in the small font (max {SCREEN_W - 4})')
        elif kind == 'label' and small > SCREEN_W - 2:
            problems.append(f'{where} = {s!r}: {small} px (max {SCREEN_W - 2})')
        elif kind == 'hello' and big > BIG_MAX:
            problems.append(f'{where} = {s!r}: {big} px (max {BIG_MAX})')
        elif kind == 'switch':
            active = text_w(s, True, cjk_bold=True)
            if max(active, small) > SWITCH_MAX:
                problems.append(f'{where} = {s!r}: {active}/{small} px big/small (max {SWITCH_MAX} beside the pill)')
if problems:
    sys.exit('gen_assets: textos.py has problems, nothing written:\n  ' + '\n  '.join(problems))
for m in small_ones:
    print('note:', m)

# softFontCJK: cjk_cell() of only the characters used.
assert len(cjk_used) < 256, 'SoftFont::count is a uint8_t'
cg, cbits, clines = [], [], []
for code in sorted(cjk_used):
    a = cjk_cell(code)
    data = pack(a)
    cg.append((code, a.shape[1], len(cbits)))
    cbits += data
    clines.append('    ' + ', '.join(f'0x{b:02X}' for b in data) + f',  // {chr(code)}')
cpp += ['// Chinese glyphs: Fusion Pixel Font 12px zh_hans (c) 2022 TakWolf, which takes them from Ark Pixel',
        '// Font (c) 2021 TakWolf and Cubic 11; SIL Open Font License 1.1. Source and licenses: tools/oled/fonts/.',
        'static const uint8_t softFontCJKBits[] PROGMEM = {'] + (clines or ['    0']) + [
        '};', 'static const SoftGlyph softFontCJKGlyphs[] PROGMEM = {']
cpp += [f'    {{0x{code:04X}, 0, {w}, {CJK_H}, {off}}}, // {chr(code)}' for code, w, off in cg]
if not cg:
    cpp.append('    {0, 0, 0, 0, 0}')
cpp += ['};', f'PROGMEM const SoftFont softFontCJK = {{softFontCJKGlyphs, {len(cg)}, softFontCJKBits, {CJK_H}, {CJK_SPACING}}};', '']
total += len(cbits) + len(cg) * 8


def cstr(s):
    """C string literal of the UTF-8 bytes (a hex escape never swallows the next character)."""
    out, after_hex = [], False
    for b in s.encode('utf-8'):
        c = chr(b)
        if 0x20 <= b < 0x7F and c not in '"\\':
            if after_hex and c in '0123456789abcdefABCDEF':
                out.append('" "')
            out.append(c)
            after_hex = False
        else:
            out.append(f'\\x{b:02X}')
            after_hex = True
    return '"' + ''.join(out) + '"'


def readable(s):
    return ''.join(ch if ch.isprintable() else f'\\x{ord(ch):02x}' for ch in s)


pool = {}


def ref(s):
    if s is None:
        return 'nullptr'
    if s not in pool:
        pool[s] = f'softTxt{len(pool)}'
    return pool[s]


tables = []
langs = ', '.join(f'{i} {c}' for i, c in enumerate(textos.LANGS))
rows = [f'    {{{ref(name)}, {{{", ".join(ref(s) for s in t)}}}}},  // {name}' for name, t in textos.FACES.items()]
tables += [f'PROGMEM const SoftFaceText softFaceTexts[SOFT_FACE_TEXTS] = {{'] + rows + ['};']
for cname, group, n in (('softSettingWords', 'SETTINGS', 13), ('softColorWords', 'COLORS', 10),
                        ('softHueWords', 'HUES', 10), ('softEffectWords', 'EFFECTS', 10)):
    rows = getattr(textos, group)
    tables.append(f'PROGMEM const char* const {cname}[SOFT_LANGS][{n}] = {{')
    for i in range(L):
        tables.append(f'    {{{", ".join(ref(t[i]) for t in rows)}}},  // {textos.LANGS[i]}')
    tables.append('};')
tables.append('PROGMEM const char* const softWords[SOFT_LANGS][SOFT_WORDS] = {')
for i in range(L):
    tables.append(f'    {{{", ".join(ref(t[i]) for t in textos.WORDS.values())}}},  // {textos.LANGS[i]}')
tables.append('};')
cpp += [f'// ---- texts (tools/oled/textos.py), by language: {langs} ----']
cpp += [f'static const char {v}[] PROGMEM = {cstr(s)};' + (f'  // {readable(s)}' if s else '') for s, v in pool.items()]
cpp += tables + ['']
total += sum(len(s.encode()) + 1 for s in pool) + 4 * (len(textos.FACES) * (L + 1) + L * (13 + 30 + len(textos.WORDS)))

hdr += [f'// ---- texts (tools/oled/textos.py) ----',
        f'static const uint8_t SOFT_LANGS = {L};   // the language number: {langs}',
        'struct SoftFaceText { const char* name; const char* label[SOFT_LANGS]; };  // nullptr = the name as is',
        f'static const uint8_t SOFT_FACE_TEXTS = {len(textos.FACES)};',
        'extern const SoftFaceText softFaceTexts[SOFT_FACE_TEXTS];  // by the faceArray name',
        'extern const char* const softSettingWords[SOFT_LANGS][13];  // index = Menu::MenuState',
        'extern const char* const softColorWords[SOFT_LANGS][10];    // Menu::GetFaceColor()',
        'extern const char* const softHueWords[SOFT_LANGS][10];      // HueF / HueB',
        'extern const char* const softEffectWords[SOFT_LANGS][10];   // Menu::GetEffectS()',
        'enum SoftWord : uint8_t { ' + ', '.join(f'WORD_{k}' for k in textos.WORDS) + ', SOFT_WORDS };',
        'extern const char* const softWords[SOFT_LANGS][SOFT_WORDS];', '']


def emit(cname, a, note=''):
    global total
    a = np.asarray(a, np.uint8)
    h, w = a.shape
    data = pack(a)
    total += len(data)
    cpp.append(f'static const uint8_t {cname}Bits[] PROGMEM = {{ ' + ', '.join(f'0x{b:02X}' for b in data) + ' };')
    cpp.append(f'PROGMEM const SoftIcon {cname} = {{{w}, {h}, {cname}Bits}};')
    hdr.append(f'extern const SoftIcon {cname};' + (f'  // {w}x{h} {note}' if note else f'  // {w}x{h}'))


def interior(a):
    """Pixels enclosed by the outline of a (flood fill from the border)."""
    h, w = a.shape
    outside = np.zeros_like(a)
    stack = [(y, x) for y in range(h) for x in (0, w - 1)] + [(y, x) for x in range(w) for y in (0, h - 1)]
    while stack:
        y, x = stack.pop()
        if 0 <= y < h and 0 <= x < w and not outside[y, x] and not a[y, x]:
            outside[y, x] = 1
            stack += [(y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)]
    return (1 - outside) & (1 - a)


# ---- setting icons (32x32) ----
for n in ('sun', 'sides', 'mic', 'ear', 'boop', 'mirror_on', 'mirror_off', 'size', 'hue', 'wand'):
    emit('icon_' + n, recenter(epx(parse(I[n])), 32, 32))
for k in range(3):  # 4 blades -> 90 deg symmetry, 3 frames 30 deg apart
    emit(f'icon_fan{k}', recenter(fan(blades=4, wmax=24, curve=3.5, R=14.0, rot=-90 + 30 * k), 32, 32),
         'fan, spins with the level')

# COLOR: the drop, filled to hint the colour mode
drop = recenter(epx(parse(I['palette'])), 32, 32)
inner = interior(drop)
ys, xs = np.nonzero(inner)
y0, y1 = ys.min(), ys.max()
inner_shrunk = inner.copy()  # keep a 1 px gap between the outline and the fill
for y, x in zip(*np.nonzero(inner)):
    if drop[max(0, y - 1):y + 2, max(0, x - 1):x + 2].any():
        inner_shrunk[y, x] = 0
bayer = np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]])
yy, xx = np.mgrid[0:32, 0:32]
grad = ((yy - y0) / max(1, y1 - y0) * 17 - 1) > bayer[yy % 4, xx % 4]   # sparse top -> dense bottom
bands = ((yy - y0) % 4) < 2
rng = np.random.RandomState(7)
noise = rng.rand(32, 32) < 0.38
emit('icon_drop', drop, 'COLOR outline')
emit('icon_drop_solid', drop | inner_shrunk, 'solid colours')
emit('icon_drop_grad', drop | (inner_shrunk & grad), 'DEGRADADO')
emit('icon_drop_bands', drop | (inner_shrunk & bands), 'ARCOIRIS')
emit('icon_drop_noise', drop | (inner_shrunk & noise), 'NEBULOSA')
hdr.append('')

# ---- warning light ----
emit('icon_coolant', epx(parse(T['coolant'])), 'engine-hot light')
emit('icon_coolant_big', epx(parse(T['coolant_big'])), 'very hot, inside the visor')
hdr.append('')

# ---- pictograms for image/video slots (12x12 art -> EPX 24x24) ----
for n in P:
    a = epx(parse(P[n]))
    if not n.startswith('kaomoji'):          # kaomoji frames keep their grid so they don't jump
        a = recenter(a, max(24, a.shape[1]), 24)
    emit('pict_' + n, a)
for n in PN:
    emit('pict_' + n, recenter(parse(PN[n]), 26, 24))
hdr.append('')
for n in S:
    emit(n, parse(S[n]))
emit('heart_big', epx(parse(S['heart_small'])))
hdr.append('')

# ---- widgets baked from the GFX ports ----
def ring(w, h, r, t=2):
    """Rounded-rect outline t px thick (filled rect minus the inset filled rect: no corner gaps)."""
    o, i = G(w, h), G(w, h)
    o.fill_round_rect(0, 0, w, h, r)
    i.fill_round_rect(t, t, w - 2 * t, h - 2 * t, r - t)
    return o.a & (1 - i.a)


EAR_H = 6
g = G(110, 31 + EAR_H)                    # visor: 2 px rounded frame + two filled cat ears
g.a[EAR_H:, :] |= ring(110, 31, 8)
for s_ in (-1, 1):
    base_out, base_in, tip = 55 + s_ * 47, 55 + s_ * 31, 55 + s_ * 43
    g.fill_triangle([(base_out, EAR_H + 1), (base_in, EAR_H + 1), (tip, 0)])
emit('wid_visor', g.a, f'frame at y+{EAR_H}, 110x31')
g = G(7, 7); g.fill_circle(3, 3, 3); emit('wid_dot_on', g.a)
g = G(7, 7); g.circle(3, 3, 3); emit('wid_dot_off', g.a)
g = G(36, 15); g.fill_round_rect(0, 0, 36, 15, 7); g.fill_circle(27, 7, 4, 0); emit('wid_toggle_on', g.a)
g = G(36, 15); g.a |= ring(36, 15, 7); g.fill_circle(8, 7, 4)
emit('wid_toggle_off', g.a)
g = G(24, 24); g.fill_round_rect(0, 0, 24, 24, 6); emit('wid_tile', g.a, 'warning-light housing')
g = G(17, 5); g.circle_helper(4, 0, 4, 12); g.circle_helper(12, 0, 4, 12); emit('wid_mouth_w', g.a)
hdr.append('')

# ---- boop gesture status line: hand + 5 progress dots, which turn into a lit capsule with a check ----
for n in BP:
    emit(n, crop(epx(parse(BP[n]))))
g = G(9, 9); g.fill_circle(4, 4, 4); emit('wid_pip_on', g.a, 'boop progress dot')
g = G(9, 9); g.circle(4, 4, 4); emit('wid_pip_off', g.a)
g = G(65, 17); g.fill_round_rect(0, 0, 65, 17, 8); emit('wid_capsule', g.a, 'boop done: the dots fused into one lit bar')

os.makedirs(out_dir, exist_ok=True)
with open(os.path.join(out_dir, 'SoftAssets.cpp'), 'w') as f:
    f.write('\n'.join(cpp) + '\n')
with open(os.path.join(out_dir, 'SoftAssets.h'), 'w') as f:
    f.write('\n'.join(hdr) + '\n')
print('SoftAssets: ~%d bytes of PROGMEM' % total)
