// GENERATED by tools/oled/gen_assets.py - edit the sources there, not this file.
#pragma once
#include <stdint.h>

struct SoftGlyph { uint16_t code; int8_t top; uint8_t w; uint8_t h; uint16_t off; };
struct SoftFont { const SoftGlyph* glyphs; uint8_t count; const uint8_t* bits; uint8_t capHeight; uint8_t spacing; };
struct SoftIcon { uint8_t w; uint8_t h; const uint8_t* bits; };

extern const SoftFont softFontS;   // 5x7 soft caps
extern const SoftFont softFontL;   // EPX 2x of the same (10x14)
extern const SoftFont softFontCJK; // 12 px Chinese, only the characters of textos.py (Fusion Pixel Font, OFL-1.1)

// ---- texts (tools/oled/textos.py) ----
static const uint8_t SOFT_LANGS = 3;   // the language number: 0 es, 1 en, 2 zh
struct SoftFaceText { const char* name; const char* label[SOFT_LANGS]; };  // nullptr = the name as is
static const uint8_t SOFT_FACE_TEXTS = 16;
extern const SoftFaceText softFaceTexts[SOFT_FACE_TEXTS];  // by the faceArray name
extern const char* const softSettingWords[SOFT_LANGS][13];  // index = Menu::MenuState
extern const char* const softColorWords[SOFT_LANGS][10];    // Menu::GetFaceColor()
extern const char* const softHueWords[SOFT_LANGS][10];      // HueF / HueB
extern const char* const softEffectWords[SOFT_LANGS][10];   // Menu::GetEffectS()
enum SoftWord : uint8_t { WORD_HELLO, WORD_FACE, WORD_OFF, WORD_ON, SOFT_WORDS };
extern const char* const softWords[SOFT_LANGS][SOFT_WORDS];

extern const SoftIcon icon_sun;  // 32x32
extern const SoftIcon icon_sides;  // 32x32
extern const SoftIcon icon_mic;  // 32x32
extern const SoftIcon icon_ear;  // 32x32
extern const SoftIcon icon_boop;  // 32x32
extern const SoftIcon icon_mirror_on;  // 32x32
extern const SoftIcon icon_mirror_off;  // 32x32
extern const SoftIcon icon_size;  // 32x32
extern const SoftIcon icon_hue;  // 32x32
extern const SoftIcon icon_wand;  // 32x32
extern const SoftIcon icon_fan0;  // 32x32 fan, spins with the level
extern const SoftIcon icon_fan1;  // 32x32 fan, spins with the level
extern const SoftIcon icon_fan2;  // 32x32 fan, spins with the level
extern const SoftIcon icon_drop;  // 32x32 COLOR outline
extern const SoftIcon icon_drop_solid;  // 32x32 solid colours
extern const SoftIcon icon_drop_grad;  // 32x32 DEGRADADO
extern const SoftIcon icon_drop_bands;  // 32x32 ARCOIRIS
extern const SoftIcon icon_drop_noise;  // 32x32 NEBULOSA

extern const SoftIcon icon_coolant;  // 20x20 engine-hot light
extern const SoftIcon icon_coolant_big;  // 20x24 very hot, inside the visor

extern const SoftIcon pict_bsod;  // 24x24
extern const SoftIcon pict_lowbat;  // 24x24
extern const SoftIcon pict_kaomoji;  // 24x24
extern const SoftIcon pict_kaomoji_x;  // 24x24
extern const SoftIcon pict_kaomoji_love;  // 24x24
extern const SoftIcon pict_heart;  // 24x24
extern const SoftIcon pict_rings;  // 24x24
extern const SoftIcon pict_eq;  // 24x24
extern const SoftIcon pict_play;  // 24x24

extern const SoftIcon spark_big;  // 7x7
extern const SoftIcon spark_small;  // 5x5
extern const SoftIcon spark_dot;  // 1x1
extern const SoftIcon heart_small;  // 5x5
extern const SoftIcon heart_big;  // 10x10

extern const SoftIcon wid_visor;  // 110x37 frame at y+6, 110x31
extern const SoftIcon wid_dot_on;  // 7x7
extern const SoftIcon wid_dot_off;  // 7x7
extern const SoftIcon wid_toggle_on;  // 36x15
extern const SoftIcon wid_toggle_off;  // 36x15
extern const SoftIcon wid_tile;  // 24x24 warning-light housing
extern const SoftIcon wid_mouth_w;  // 17x5

extern const SoftIcon boop_hand;  // 18x18
extern const SoftIcon icon_check;  // 18x12
extern const SoftIcon wid_pip_on;  // 9x9 boop progress dot
extern const SoftIcon wid_pip_off;  // 9x9
extern const SoftIcon wid_capsule;  // 65x17 boop done: the dots fused into one lit bar
