/**
 * @file SSD1306.h
 * @brief HeadsUpDisplay: the small SSD1306/SH1106 OLED inside the head ("visorcito").
 *
 * Like a car dashboard at night:
 *  - Normal use shows only which face is on: a little visor with the live face (both panels,
 *    as people see them) and the face's name. Image/video slots get a pictogram.
 *  - The chip temperature is a warning light, never a number: nothing while it is fine, a
 *    blinking "engine hot" light (thermometer in waves) when hot, and the whole visor lit
 *    with the light cut out, blinking fast, when very hot.
 *  - Settings only appear while editing them with the button: one big icon, a short word and
 *    the value as dots, an off/on switch or a word. No digits anywhere.
 *  - Words in Spanish, English or Simplified Chinese (SetLanguage; the text tables of SoftAssets
 *    come from tools/oled/textos.py). -D IDIOMA_DEFECTO=<N> is the default, the project saves
 *    the choice (serial l<N>, EEPROM 201).
 *  - Boop + boooop (BoopGesture): while it is being done the name line becomes a status line,
 *    so the wearer can tell whether the head caught it: a pointing hand + 5 dots that fill (1st
 *    boop, then the hold), a lit bar with a check when it fires (then the new name + sparkles),
 *    the dots just empty out if they let go early. A plain single boop simply goes away. On the edit
 *    screens only the hand / a check tile shows, top right. While a finger is on the sensor for
 *    the 1st boop (at most 350 ms) the 5 Hz frames wait, so the bus is free the moment it is
 *    caught (not when very hot: that light keeps its blink).
 *
 * Fonts, icons and every word live in SoftAssets.* (generated by tools/oled/gen_assets.py).
 *
 * @date 22/12/2024 (original layout by Coela Can't), redesign 2026-10
 * @author Coela Can't (original HeadsUpDisplay); redesigned in the MochiiTracer fork
 */

#pragma once

#include <Arduino.h> // Include for Arduino compatibility.
#include <Wire.h> // Include for I2C communication.
#include <Adafruit_GFX.h> // Include for Adafruit GFX library.

#include "../../Examples/UserConfiguration.h" // Include for user-specific configurations.
#include "../InputDevices/Menu/Menu.h" // Include for menu input handling.
#include "../../Utils/Math/Mathematics.h" // Include for mathematical utilities.
#include "../../Scene/Screenspace/Effect.h" // Include for effect interface.
#include "../../Utils/Time/TimeStep.h" // Include for timestep utility.
#include "SoftAssets.h" // Soft pixel fonts, icons and the words in every language.
#include "../../Examples/Protogen/BoopGesture.h" // Stage/Event names for SetBoopGesture (Arduino-free)

// Language of the words on the screen: 0 español, 1 English, 2 简体中文 (SoftAssets' SOFT_LANGS).
// The default of the build (-D IDIOMA_DEFECTO=<N>); the project switches it at run time.
#ifndef IDIOMA_DEFECTO
#define IDIOMA_DEFECTO 0
#endif
static_assert(IDIOMA_DEFECTO >= 0 && IDIOMA_DEFECTO < SOFT_LANGS, "IDIOMA_DEFECTO: 0 es, 1 en, 2 zh");

#ifndef FLASHMEM
#define FLASHMEM // Teensy 4: keeps this 5 Hz UI code in flash instead of the ITCM part of RAM1
#endif
// LTO (-O3) would inline small FLASHMEM helpers into their ITCM callers (the project's Update),
// which puts them back in RAM1: the boop helpers are kept out of line on purpose.
#define HUD_COLD FLASHMEM __attribute__((noinline))

#ifdef SH1106
#include "Adafruit_SH1106.h" // Include for SH1106 display (untested).
#else
#include <Adafruit_SSD1306.h> // Include for SSD1306 display.
#endif

class HeadsUpDisplay : public Effect {
private:
    static const uint16_t SCREEN_WIDTH = 128;
    static const uint16_t SCREEN_HEIGHT = 64;
    static const int8_t OLED_RESET = -1;

    // --- tuning -------------------------------------------------------------------------------
    // Temperature warning light (Teensy chip, tempmonGetTemp(); ~46 C normal), with hysteresis.
    static constexpr float hotOnC = 70.0f;      ///< "engine hot" light starts blinking gently
    static constexpr float hotOffC = 65.0f;     ///< ...and goes away below this
    static constexpr float veryHotOnC = 80.0f;  ///< whole visor lit, fast blink
    static constexpr float veryHotOffC = 75.0f;

    static const uint8_t contrastCalm = 0x7F;   ///< normal use: a dimmed "night dashboard"
    static const uint8_t contrastActive = 0xCF; ///< editing, right after a face change, warnings

    static const uint32_t creditTime = 900;     ///< ProtoTracer / AGPL credit at power on
    static const uint32_t bootTime = 3100;      ///< cute boot after the credit (~4 s total, like the LED boot)
    static const uint32_t wakeTime = 1500;      ///< full contrast after a face change / leaving the menu...
    static const uint32_t fadeTime = 600;       ///< ...then back to calm in a few steps
    static const uint32_t sparkleTime = 1200;   ///< sparkles (hearts for AMOR) around a new face's name
    static const uint32_t driftTime = 60000;    ///< burn-in care: the idle picture moves 1 px once a minute
    static const uint16_t refreshEvery = 10;    ///< resend an unchanged frame every N updates anyway (2 s)
    static const uint8_t defaultFaceSlots = 20; ///< bound for the face index if SetFaceArray got no count

    // Boop gesture status line. Outside a gesture nothing changes (same 5 Hz frames, same bytes).
    static const uint32_t boopMinGap = 100;     ///< during a gesture: at most 10 frames/s on the shared I2C bus
    static const uint32_t boopDoneTime = 500;   ///< lit bar + check after it fires, then the new name + sparkles
    static const uint32_t boopFizzleTime = 350; ///< let go early: the dots stay empty this long, then the name
    static const uint32_t boopCornerTime = 1200;///< edit screens: the check tile (the face changed underneath)
    static const uint8_t boopDots = 5;          ///< 1st boop = 1, 2nd boop caught = 2, then 3/4/5 while held
    // Dots while the 2nd boop is held (ms of HoldMs). A normal double tap (2nd press up to ~300 ms)
    // must never look like progress, and HoldMs keeps running after she lets go while the gesture
    // makes sure (RELEASE_MS), plus up to one slow 39 ms frame of sampling skew: a 300 ms press
    // reads up to 300 + 39 + 80 (measured 372 in the sim), so the 3rd dot waits until 420. Then a
    // steady beat: 4th, 5th, and the check at HOLD_MS (800).
    static const uint32_t boopDot3At = 420;
    static const uint32_t boopDot4At = 545;
    static const uint32_t boopDot5At = 670;
    static_assert(boopDot3At >= 300 + 39 + BoopGesture::RELEASE_MS && boopDot5At < BoopGesture::HOLD_MS, "boop dot schedule");
    // Contrast: true = the 1st boop already lights the panel up (0xCF) with the hand; false = it
    // stays calm and only the 2nd boop (HOLD_START) brightens it (quieter for strangers' boops).
    static const bool boopBrightAtTap = true;

    // --- layout ---------------------------------------------------------------------------------
    // Mini face: one camera half (64x32) drawn as [mirror | normal] at 4/5 scale -> 102x25.
    static const uint8_t srcW = 64;
    static const uint8_t srcH = 32;
    static const uint8_t halfW = (srcW - 1) * 4 / 5 + 1;   // 51 (and 25 rows tall)
    static const int16_t visorTop = 3;                     // tips of the ears
    static const int16_t frameX = 9, frameY = visorTop + 6, frameW = 110, frameH = 31;
    static const int16_t faceX = 64 - halfW, faceY = frameY + 3;
    static const int16_t nameY = 47;                       // top of the caps of the face name
    static const int16_t boopLineX = 21;                   // hand (18) + 8 + 5 dots at 13 px = 87 wide, centred
    static const int16_t boopPitch = 13;

    static const uint16_t cjkFirst = 0x2E80;    ///< code points from here up come from softFontCJK

    const char* const defaultFaceNames[10] = {"DEFAULT", "ANGRY", "DOUBT", "FROWN", "LOOKUP", "SAD", "AUDIO1", "AUDIO2", "AUDIO3", ""};

    const __FlashStringHelper** faceNames = nullptr; ///< Names of each face (from the project)
    uint8_t faceCount = 0;
    bool useExternalFace = false;

    Effect* subEffect = nullptr; ///< Used to capture the complete rendered frame
    TimeStep timeStep = TimeStep(5); ///< 5 updates per second (the I2C bus is shared with the boop sensor)
    bool didBegin = false;
    bool splashFinished = false;
    Vector2D faceMin;
    Vector2D faceMax;
    uint32_t startMillis = 0;

    // state
    uint8_t lang = IDIOMA_DEFECTO;  ///< language of the words (0 es, 1 en, 2 zh)
    uint32_t updateCount = 0;
    uint8_t warnLevel = 0;          ///< 0 normal, 1 hot, 2 very hot
    uint8_t warnTick = 0;           ///< blink phase, restarts (lit) when the level changes
    float tempOverride = 0.0f;      ///< serial 'w<N>': pretend N C (0 = real sensor). Not saved.
    uint8_t contrastNow = 0;
    int16_t lastFace = -1;
    bool wasEditing = false;
    uint32_t faceChangedAt = 0;
    uint32_t wakeAt = 0;
    const char* faceLabel = "";
    const SoftIcon* facePict = nullptr;  ///< pictogram for image/video slots (by name), else null
    const SoftIcon* blankPict = nullptr; ///< shown when this live face renders nothing (AUDIO*)
    const SoftIcon* nameDeco = nullptr;  ///< heart_big for AMOR, else sparkles
    int8_t ox = 0, oy = 0;               ///< burn-in drift of the idle picture
    uint16_t largestGroup = 0;           ///< pixel count of the main camera (side cameras are smaller)
    uint32_t lastHash = 0;
    uint16_t sameFrames = 0;

    // boop gesture (latched from SetBoopGesture, which runs every frame; the HUD draws far less often)
    enum BoopMode : uint8_t { BOOP_OFF, BOOP_TRACK, BOOP_DONE, BOOP_FIZZLE };
    enum BoopLookCode : uint8_t { LOOK_NONE = 0, /* 1..boopDots = dots lit */ LOOK_FIZZLE = 6, LOOK_DONE, LOOK_CORNER, LOOK_CORNER_DONE };
    uint8_t boopMode = BOOP_OFF;
    uint8_t boopStage = 0;
    uint16_t boopHoldMs = 0;
    uint32_t boopAt = 0;            ///< when it fired / fizzled
    uint8_t boopLook = LOOK_NONE;   ///< what this frame draws
    uint8_t drawnLook = LOOK_NONE;  ///< what the panel shows
    uint8_t litLook = LOOK_NONE;    ///< status line that held the panel bright on the last face frame
    bool framePending = false;      ///< a 5 Hz beat waiting for the bus gap (or for the 1st boop to end)
    bool sentOnce = false;
    uint32_t lastSentAt = 0;        ///< start of the last display()

#ifdef SH1106
    static Adafruit_SH1106 display;
#else
    static Adafruit_SSD1306 display;
#endif
    static uint8_t faceBits[srcW * srcH / 8]; ///< latest camera frame, 1 bit per LED, row 0 = top

    static const uint8_t PrototracerSplash[];

    // drawing helpers
    // Text: UTF-8 up to 3 bytes. Latin from `font` (bold = drawn twice, 1 px apart); Chinese from
    // softFontCJK on the same centre line, plain unless cjkBold (only the switch's active word).
    const SoftGlyph* FindGlyph(const SoftFont& font, uint16_t code) const;
    const SoftGlyph* PickGlyph(const SoftFont& font, uint16_t code, const SoftFont*& from) const;
    static uint16_t NextCode(const char*& s);
    int16_t TextWidth(const char* s, const SoftFont& font, bool bold = false, bool cjkBold = false) const;
    int16_t DrawText(const char* s, int16_t x, int16_t y, const SoftFont& font, bool bold = false, uint16_t color = 1, bool cjkBold = false);
    int16_t DrawTextCentered(const char* s, int16_t cx, int16_t y, const SoftFont& font, bool bold = false, uint16_t color = 1);
    void DrawIcon(const SoftIcon& icon, int16_t x, int16_t y, uint16_t color = 1);
    void DrawSlash(int16_t x, int16_t y, int16_t size);
    void DrawDots(int16_t cy, uint8_t filled, uint8_t total);
    void DrawToggle(int16_t cy, bool on);

    // screens
    void DrawCredit();
    void DrawBoot(uint32_t t);
    void DrawFaceScreen(uint32_t now, bool warnOn);
    void DrawEditScreen(uint8_t menu);
    void DrawMiniFace(uint32_t now);
    void DrawVisor();
    void DrawFaceName(uint32_t now);
    void DrawCornerLight();
    void DrawBoopLine();
    void DrawBoopCorner();
    uint8_t BoopLook(uint32_t now) const;

    const char* FaceName(uint8_t index) const;
    void PickFaceLooks(uint8_t index);
    uint8_t IdleContrast(uint32_t now, bool warnOn) const;
    void UpdateWarnLevel();
    void SetContrast(uint8_t contrast);
    void SendFrame(bool beat);
    void ResetDisplayBuffer();

    /// Shows the latest frame (kept for compatibility with the old name).
    void UpdateFaceInformation();

public:
    HeadsUpDisplay(Vector2D faceMin, Vector2D faceMax);

    /// @param count number of entries in faceNames (bounds the face index; 0 = defaultFaceSlots).
    void SetFaceArray(const __FlashStringHelper** faceNames, uint8_t count = 0);
    void SetFaceMin(Vector2D faceMin);
    void SetFaceMax(Vector2D faceMax);
    void Initialize();
    void ResetI2CBus();
    void Update();
    void SetEffect(Effect* effect);

    /// Every frame, right after the boop gesture's Update(): stage = BoopGesture::Stage,
    /// holdMs = BoopGesture::HoldMs() (clamped), event = what Update() returned (NONE most frames).
    void SetBoopGesture(uint8_t stage, uint16_t holdMs, uint8_t event);
    void ApplyEffect(IPixelGroup* pixelGroup);

    static const uint8_t LANGUAGES = SOFT_LANGS;
    /// Words in language `language` (0 es, 1 en, 2 zh) from the next frame on; out of range (an
    /// unwritten EEPROM byte = 255) = IDIOMA_DEFECTO.
    void SetLanguage(uint8_t language);
    uint8_t GetLanguage() const;

    /// Debug: pretend the chip is at `celsius` to check the warning light (0 = real sensor again).
    void SetTempOverride(float celsius);
    float GetTempOverride() const;

    /// 128x64 frame last composed (what the panel shows): 8 pages of 128 bytes, bit 0 = top row
    /// of the page (SSD1306 layout). nullptr when the OLED was not found at boot.
    const uint8_t* GetBuffer() const;
    bool IsInverted() const;    ///< true if the panel inverts the buffer (bit 0 = lit). Always false now.
    uint8_t GetContrast() const;
};
